### PR TITLE
Renaming pass

### PR DESCRIPTION
**Pull request by pascutto**
This follows #40.
The changes are described in commit messages : 

- ~~Unused variable names (eg in pattern matchings) are replaced with `_`.~~
- `logdata_contents` was renamed `contents`.
- `wodan_crc32c` was renamed `crc32c`, and `wodan_statistics` was renamed `statistics`.
- `childlinks` type has been removed and `childlinks` was renamed `childlinks_offset` in `lru_entry`.
- Leading underscores in function names have been removed.
- `lru_entry` was renamed `node`.
- The library was wrapped.
- Tests were moved from `irmin-tests` to `tests/wodan_irmin`.
- Examples were moved from `solo5-*` to `examples/solo5-*`.

### CODE REVIEW

**Comment by g2p** [comment]
I like most of these.

> * Unused variable names (eg in pattern matchings) are replaced with `_`.

I prefer knowing what the variables refer to when editing.

> * `logdata_contents` was renamed `contents`.
> * `wodan_crc32c` was renamed `crc32c`.

We're using (wrapped false), so this change would pollute the global namespace.

> * `childlinks` type has been removed and `childlinks` was renamed `childlinks_offset` in `lru_entry`.
> * Leading underscores in function names have been removed.
> * `lru_entry` was renamed `node`.

Otherwise, great.

**Comment by pascutto** [comment]
> We're using (wrapped false), so this change would pollute the global namespace.

I had not seen that. Why are we doing this ? It feels like `keyedmap` should be prefixed too then, or we should switch `wrapped` to true (I prefer this solution).

**Comment by pascutto** [comment]
I rebased and reverted the unused variables thing.

**Review by g2p — COMMENTED** [review]
It's a bit dirty copying the small CRC32C wrapper like that, but I guess since we don't want to make it public it's an understandable workaround.
As a minor remark, have you tried matching directory names of packages/src/tests? tests/wodan-irmin would be better.
Apart from that, looking good.

**Comment by pascutto** [comment]
I agree about the copying thing, but as you said, I don't think we want to have that public, and dune does not allow a public library to depend on a private one for now (see https://github.com/ocaml/dune/issues/1017).
Fixed the test directory ! :heavy_check_mark:

**Review by g2p — APPROVED** [review]
Thanks!

**Pull request merged**
