### PR TITLE
Unvendor Diet

### PR DESCRIPTION
**Pull request by g2p**
Diet 0.3 has been released, with no outstanding patches,
so stop vendoring it.
Thanks @avsm.

### CODE REVIEW

**Comment by pascutto** [comment]
Thanks !
I can't find where we were using that `find_next_gap` function though, and I can compile with `diet.0.2`.

**Comment by g2p** [comment]
I've kept uses of find_next_gap in a branch. It's an optimisation for when disks are mostly full, and I want to focus on bugfixing first.

**Comment by pascutto** [comment]
Okay, then I guess we should have diet to `>= "0.2"` in master, and you can include the `>= "0.3"` constraint in your PR when it's ready.

**Comment by g2p** [comment]
Sure, done.

**Review by pascutto — APPROVED** [review]

**Pull request merged**
