### PR TITLE
Update to Irmin dev

### PR DESCRIPTION
**Pull request by pascutto**
This PR updates wodan to use the latest version of Irmin.

### CODE REVIEW

**Comment by pascutto** [comment]
This should be ready for review.
I noticed that Irmin tests are failing when testing `Make` and `KV` for instance, but that happened before that PR so it should be addressed elsewhere.

**Comment by g2p** [comment]
I think I'd prefer if the dependencies you pinned came from vendored directories.
This has several advantages:
- we know what we are building against exactly
- we can use dune to build without pinning, shortening the development cycle by a lot (no Opam bottleneck)

Additionally, if you remove all vendored directories, you lose forks which currently contain additional functionality, such as additional mirage interfaces for flushing.

**Comment by pascutto** [comment]
Regarding pins, I think they are always needed, even when Irmin is in a vendored directory, so that opam gets the correct dependencies.

Regarding forks, can we upstream these additional functionalities ?

**Comment by g2p** [comment]
On the first point, we should be installing dependencies from the vendored opam files instead.
(I used to list them manually, but that got removed when you updated the CI).
I can send a PR for this (#53).

Re upstreaming, that's what we'll do eventually, but I think the interfaces should be tested first to see if everything works well and there's no missing functionality.

**Comment by samoht** [comment]
The usual way to test "forked" universe is to add a branch in https://github.com/mirage/mirage-dev and put link to your forks package there, while opening PRs on the various projects you are forking.

See how @hannesm is managing [large updates to the network stack](https://github.com/mirage/mirage-protocols/pull/16).

Also always using the dev version of irmin is a burden but has the right incentive to make us fix any issue we could find as early as possible. If that's the case feel free to ping me directly and I can help (or anyone else in the @mirage/core team). For instance I was not aware that wodan was still using an old version of irmin...

**Comment by g2p** [comment]
I'm willing to accept dropping the Irmin vendored stuff to work the way @samoht recommends, with the understanding that Irmin people can help undo CI breakage.

About forking parts of the Mirage stack, sure, it could work, but the current PR just drops a working workflow without providing a replacement (which is possible because flushing is still WIP).
I'm not willing to drop the working solution when there's no replacement.
And I'd much rather review workflow changes and code changes (like the main thrust of this PR) independently.

**Comment by hannesm** [comment]
to explain what I do if I need to stage + CI changes crossing several repositories:
- (a) create a fresh branch in mirage-dev (there's a CI which clones mirage-skeleton and compiles all example unikernels on most targets)
- (b) I add those packages in there (by putting an opam file there which url points to my clone on a specific branch)
   - important: easiest to name all the branches the same, i.e. `layering` or `rename-ethif`
   - version numbers: pick whichever you like - usually increasing major or minor version helps to be able to add proper constraints to all other packages
- (c) in the other repositories I modify `travis.yml` to include `EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git#<mybranch>"` -- this makes sure they're used during the CI run
- (d) once changes are done and CI is happy, changes can be merged to master and released. since version numbers have already been selected, the constraints can as well be already in the opam files. the downside is that the changes to `travis.yml` need to be reverted in all the repositories

to reproduce on a different switch/computer, I no longer need to remember the 25 pins I have, but can as well just add the mirage-dev opam repo (on a branch) as another repo. this works until i want to modify some pins before pushing to github, and then i have to manually pin some libraries.

my attempts to use git submodules or subdirectories are always failing (I'm just bad at git).

now, with the new dune/duniverse setup, I hope that at least locally i don't have to do the opam pin games anymore, but can have some magic to get the repos i'm interested in on a certain branch and just run dune build.

**Comment by emillon** [comment]
In addition, I'd like to point out that in many cases, there is no need to vendor at all: for example, to add `Diet.iter`, it is also possible to define `diet_iter` in wodan itself, submit a PR, and remove the function when the dependency is bumped.

**Comment by pascutto** [comment]
Rebased and restored mirage-block-*

**Review by g2p — APPROVED** [review]
Taking this minus the pinning changes.
Will follow up with a way to auto-refresh the pins in Travis.

**Comment by dinosaure** [comment]
image

I like it.

**Comment by g2p** [comment]
Removal of my ugly generated mli; that's indeed much better.

**Pull request merged**
